# Railway Configuration - Backend Only
# This is a simple single-service configuration for your backend

services:
  backend:
    # Tell Railway to look in the backend folder
    root: backend
    
    build:
      # Use Dockerfile for consistent builds
      builder: DOCKERFILE
      dockerfilePath: Dockerfile
    
    deploy:
      healthcheckPath: /health
      healthcheckTimeout: 100
      restartPolicyType: ON_FAILURE
      restartPolicyMaxRetries: 10
    
    env:
      PORT: 8000
      RELOAD: false
      # For local Ollama, use: http://localhost:11434
      # For Railway Ollama service, use: http://${{ollama.RAILWAY_PRIVATE_DOMAIN}}:11434
      OLLAMA_HOST: http://localhost:11434
