"""
Helper utilities for the workflow

This module provides utility functions for formatting output,
validating input, and other common tasks.
"""

import json
import textwrap
from typing import Dict, Any, Optional
from ..graph.state import TextAnalysisState


def validate_input(
    text: str, min_length: int = 10, max_length: int = 10000
) -> tuple[bool, Optional[str]]:
    """
    Validate input text

    Args:
        text: Input text to validate
        min_length: Minimum required length
        max_length: Maximum allowed length

    Returns:
        Tuple of (is_valid, error_message)

    Example:
        >>> is_valid, error = validate_input("Sample text")
        >>> if not is_valid:
        ...     print(error)
    """
    if not text:
        return False, "Input text cannot be empty"

    if not isinstance(text, str):
        return False, "Input must be a string"

    text = text.strip()

    if len(text) < min_length:
        return False, f"Input text must be at least {min_length} characters"

    if len(text) > max_length:
        return False, f"Input text must not exceed {max_length} characters"

    return True, None


def format_result(state: TextAnalysisState, format_type: str = "text") -> str:
    """
    Format workflow result for display

    Args:
        state: Final state from workflow execution
        format_type: Output format ('text', 'json', or 'markdown')

    Returns:
        Formatted string representation of the result

    Example:
        >>> result = workflow.invoke({"input_text": "..."})
        >>> print(format_result(result, "markdown"))
    """
    if format_type == "json":
        return json.dumps(state, indent=2)

    elif format_type == "markdown":
        return f"""# Text Analysis Results

## Input
- **Length**: {len(state.get('input_text', ''))} characters
- **Word Count**: {state.get('word_count', 0)} words

## Analysis

### Summary
{textwrap.fill(state.get('summary', 'No summary available'), width=80)}

### Sentiment
**{state.get('sentiment', 'Unknown').upper()}**

---
*Generated by LangGraph Text Analysis Workflow*
"""

    else:  # Default to text format
        return f"""
{'=' * 70}
TEXT ANALYSIS RESULTS
{'=' * 70}

INPUT STATISTICS:
  - Characters: {len(state.get('input_text', ''))}
  - Words: {state.get('word_count', 0)}

SUMMARY:
{textwrap.fill(state.get('summary', 'No summary available'), width=80)}

SENTIMENT:
  {state.get('sentiment', 'Unknown').upper()}

{'=' * 70}
"""


def print_result(state: TextAnalysisState, format_type: str = "text") -> None:
    """
    Print workflow result to console

    Args:
        state: Final state from workflow execution
        format_type: Output format ('text', 'json', or 'markdown')

    Example:
        >>> result = workflow.invoke({"input_text": "..."})
        >>> print_result(result)
    """
    print(format_result(state, format_type))


def truncate_text(text: str, max_length: int = 100, suffix: str = "...") -> str:
    """
    Truncate text to a maximum length

    Args:
        text: Text to truncate
        max_length: Maximum length
        suffix: Suffix to append if truncated

    Returns:
        Truncated text

    Example:
        >>> truncate_text("This is a long text", 10)
        'This is a...'
    """
    if len(text) <= max_length:
        return text
    return text[: max_length - len(suffix)] + suffix


def extract_key_stats(state: TextAnalysisState) -> Dict[str, Any]:
    """
    Extract key statistics from state

    Args:
        state: Workflow state

    Returns:
        Dictionary of key statistics

    Example:
        >>> stats = extract_key_stats(result)
        >>> print(stats['avg_word_length'])
    """
    input_text = state.get("input_text", "")
    word_count = state.get("word_count", 0)

    stats = {
        "character_count": len(input_text),
        "word_count": word_count,
        "avg_word_length": len(input_text) / word_count if word_count > 0 else 0,
        "has_summary": bool(state.get("summary")),
        "sentiment": state.get("sentiment", "unknown"),
    }

    return stats


def create_sample_inputs():
    """
    Create sample inputs for testing

    Returns:
        List of sample input texts
    """
    return [
        "Artificial intelligence is transforming the way we live and work. From healthcare to transportation, AI systems are becoming increasingly sophisticated and capable. However, this rapid advancement also raises important questions about ethics, privacy, and the future of human employment.",
        "The beautiful sunset painted the sky with vibrant shades of orange, pink, and purple. Birds chirped their evening songs as the day slowly came to an end. It was a peaceful moment that reminded everyone to appreciate the simple beauty of nature.",
        "The company's quarterly earnings fell short of expectations, causing stock prices to drop by 15 percent. Investors expressed concerns about the future outlook, and analysts are recommending caution in the technology sector.",
        "Scientists have made a groundbreaking discovery in renewable energy. The new solar panel design is 40 percent more efficient than current models and could revolutionize the way we generate clean energy.",
        "The recipe calls for three cups of flour, two eggs, and a pinch of salt. Mix all ingredients until you get a smooth batter. Bake at 350 degrees for 25 minutes or until golden brown.",
    ]
